### ISSUE TITLE
can not compile

### ISSUE THREAD

**Issue by ziyouchutuwenwu** [tonyrog/modbus#1]
hi, can not compile under debian10

rebar.config look like this:
```txt
{erl_opts, [encrypt_debug_info]}.

{deps, [
    {modbus, ".*", {git, "https://github.com/tonyrog/modbus", {branch, "master"}}}
]}.


{shell, [
  % {config, "config/sys.config"},
    {apps, [modbus_demo]}
]}.

{pre_hooks, [
  {clean, "rm -rf ./_build/test"}
]}.
{provider_hooks, [{pre, [{clean}]}]}.
{shell, [{script_file, "on_app_start.erl"}]}.

{cover_enabled, true}.
{eunit_opts, [
    verbose, {
        report,{
            eunit_surefire,[
                {dir,"./_build/test"}
            ]
        }
    }
]}.
```

i run with `rebar3 shell`, it compiled with errors
```bash
===> Compiling _build/default/lib/esockd/src/esockd_transport.erl failed
_build/default/lib/esockd/src/esockd_transport.erl:20: can't find include lib "ssl/src/ssl_api.hrl"

_build/default/lib/esockd/src/esockd_transport.erl:40: record sslsocket undefined
```

but i have installed erlang-nox erlang-src erlang-dev, and i opened _build/default/lib/esockd/src/esockd_transport.erl with idea, press ctrl and click the "ssl/src/ssl_api.hrl", and file opened.

![2222](https://user-images.githubusercontent.com/7458713/87498835-5cecd480-c68b-11ea-8ee1-e4a9428b2777.png)

thank you very much!

**Comment by tonyrog** [comment]
Does not look like rebar.config in modbus, have you installed ssl?
